backend:
  name: github
  repo: zilindeng/ysdn.info

media_folder: static/assets
public_folder: /assets

# publish_mode: editorial_workflow


collections:
  - label: "2019 Graduates"
    name: "class2019"
    folder: "src/content/graduates"
    create: true
    filter: {field: "year", value: "2019"}
    fields:
      - {label: "Path", name: "path", required: true }
      - {label: "Name", name: "name", required: true }
      - {label: "Website", name: "website", required: false }
      - {label: "Year", name: "year", widget: "select", options: ["2019", "2018", "2017", "2016"], required: true}

  - label: "2018 Graduates"
    name: "class2018"
    folder: "src/content/graduates"
    create: true
    filter: {field: "year", value: "2018"}
    fields:
      - {label: "Path", name: "path", required: true }
      - {label: "Name", name: "name", required: true }
      - {label: "Website", name: "website", required: false }
      - {label: "Year", name: "year", widget: "select", options: ["2019", "2018", "2017", "2016"], required: true}

  - label: "2017 Graduates"
    name: "class2017"
    folder: "src/content/graduates"
    create: true
    filter: {field: "year", value: "2017"}
    fields:
      - {label: "Path", name: "path", required: true }
      - {label: "Name", name: "name", required: true }
      - {label: "Website", name: "website", required: false }
      - {label: "Year", name: "year", widget: "select", options: ["2019", "2018", "2017", "2016"], required: true}

  - label: "2016 Graduates"
    name: "class2016"
    folder: "src/content/graduates"
    create: true
    filter: {field: "year", value: "2016"}
    fields:
      - {label: "Path", name: "path", required: true }
      - {label: "Name", name: "name", required: true }
      - {label: "Website", name: "website", required: false }
      - {label: "Year", name: "year", widget: "select", options: ["2019", "2018", "2017", "2016"], required: true}


